using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace ArtApi.Models
{
    public class Artist
    {
        //The ID will be automatically generated by the Database
        public int ID { get; set; }
        public string Name { get; set; }
        public string Country { get; set; }
        public string Art { get; set; }
        
    }
}